### PR TITLE
update debian version

### PR DESCRIPTION
**Pull request by alavieille**

### CODE REVIEW

**Comment by nicolasThal** [comment]
I am not sure about the requirement changes !!

We should ask @nbouquet to check if the php 5.6 is a valid option

**Comment by ngilain** [comment]
I agree but it applies to the entire migration under debian 8.2: quid from apc vs opcache, the upgrades of mongo and apache ?

**Comment by juchi** [comment]
As software vendors, i'm don't think you can reasonably bump the software requirements of the application like you want. Even more between 2 minor versions.

**Comment by ngilain** [comment]
@nicolasThal , @itkg-alavieille , @itkg-nanne : this must be reviewed

**Comment by alavieille** [comment]
:+1:

**Pull request merged**
