### PR TITLE
summary

### PR DESCRIPTION
**Pull request by itkg-rboessel**

### CODE REVIEW

**Comment by juchi** [comment]
i think the file template_creation.rst is not part of this PR ;)

**Comment by juchi** [comment]
Do we agree that this file will be the index of the documentation and there that we should format it in rst and add the links to the pages that are already done ?
UPDATE : confirmed

**Comment by nicolasThal** [comment]
I think that we should also put some link on the already written part

**Comment by juchi** [comment]
Proposed changes :
API and routing should be in the developer guide
Remove the "advanced" title
Remove Theme from the user guide

**Comment by nicolasThal** [comment]
Proposed change : 
As said in https://github.com/open-orchestra/open-orchestra-docs/pull/20 we should add an entry on how the plateform can support a new media type

**Comment by nicolasThal** [comment]
I will merge this pr.

All remarks should be done by PR with a title starting with [Summary]

@itkg-ngilain @itkg-nanne @itkg-bfouche @itkg-rboessel @itkg-nbouquet @itkg-alavieille

**Pull request merged**
